from src.chatbot.bot import generate_dynamic_medical_report
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, white
import io
import uuid
from datetime import datetime
import sys

print('DEBUG: starting')
try:
    report = generate_dynamic_medical_report('Mild', request_id='dbg-run', strict=True)
    print('REPORT TYPE:', type(report))
    for k,v in report.items():
        print(k, '->', type(v), 'len', len(v))
except Exception as e:
    import traceback
    traceback.print_exc()
    sys.exit(1)

# Build PDF in-memory same as app
report_date = datetime.now().strftime('%d-%m-%Y')
report_time = datetime.now().strftime('%H:%M:%S')
report_id = str(uuid.uuid4())[:12].upper()

buffer = io.BytesIO()
doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=0.6*inch, leftMargin=0.6*inch, topMargin=0.6*inch, bottomMargin=0.6*inch)
styles = getSampleStyleSheet()
section_header_style = ParagraphStyle('SectionHeader', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=11, textColor=white, backColor=HexColor('#0B61B1'), leftIndent=6, rightIndent=6, spaceBefore=10, spaceAfter=6)
normal_style = ParagraphStyle('Normal', parent=styles['Normal'], fontName='Helvetica', fontSize=10, leading=13, textColor=HexColor('#333333'))
footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontName='Helvetica', fontSize=9, textColor=HexColor('#777777'), alignment=TA_CENTER)

story = []
story.append(Spacer(1,8))
story.append(Paragraph('CareSense AI', styles['Heading1']))
story.append(Paragraph('Diabetic Retinopathy Analysis Report', styles['Heading2']))
story.append(Spacer(1,8))

# Add meta
from reportlab.platypus import Table
meta_table = Table([
    ['Report Date:', report_date, 'Report Time:', report_time],
    ['Unique Report ID:', report_id, '', '']
], colWidths=[1.2*inch,2.0*inch,1.2*inch,1.2*inch])
story.append(meta_table)
story.append(Spacer(1,12))

# Add content sections
for key in ['Clinical Interpretation','Disease Summary','Possible Medical Concerns','Treatment Guidance','Lifestyle Recommendations','Follow-up Advice','Medical Disclaimer']:
    val = report.get(key,'')
    story.append(Paragraph(key.upper(), section_header_style))
    story.append(Spacer(1,6))
    story.append(Paragraph(val, normal_style))
    story.append(Spacer(1,8))

story.append(Paragraph('Generated by CareSense AI', footer_style))

print('About to build PDF...')
try:
    doc.build(story)
    print('doc.build completed')
except Exception as e:
    import traceback
    traceback.print_exc()
    sys.exit(2)

buffer.seek(0)
data = buffer.getvalue()
print('PDF bytes', len(data))
open('debug_test_retina.pdf','wb').write(data)

# Validate with pypdf if available
try:
    from pypdf import PdfReader
    r = PdfReader('debug_test_retina.pdf')
    print('pypdf pages', len(r.pages))
    text = ''.join([p.extract_text() or '' for p in r.pages])
    print('extracted length', len(text))
except Exception as e:
    print('pypdf not available or failed', e)

print('DEBUG: done')
